### ISSUE TITLE
Focus not working on US.

### ISSUE THREAD

**Issue by andreizet** [themustafaomar/jsvectormap#129]
Hey!

It seems that there is an issue with focusOn when setting the region or regions to US. On any other region, the focus works as it should.

https://codepen.io/andreizet/pen/YzORLNy?editors=0110

**Comment by themustafaomar** [comment]
Hi @andreizet 

Unfortenatuly, the US has a special known case because the path takes the full width, it's impossible to focus on the US by region name.

![image](https://github.com/themustafaomar/jsvectormap/assets/46113191/c3a608fa-ce21-45ca-a725-ae3c16a188f2)

However there's another way, you can focus using the coordinates, example:

```js
const map = new jsVectorMap({
  ...
  focusOn: {
    coords: [37.0902, -95.7129],
    scale: 5,
    animate: true,
  },
  ...
})

```

**Comment by andreizet** [comment]
@themustafaomar it makes sense, indeed!

For everyone else having the same issue as I did, another solution is to focus on Mexico and Canada:
`regions: ['CA', 'MX']`
