### ISSUE TITLE
addMarkers method problem

### ISSUE THREAD

**Issue by o2sevruk** [themustafaomar/jsvectormap#42]
Hello guys!

I've got a problem with adding markers via provided method addMarkers:

```
const test = new jsVectorMap({
  selector: '.js-jsvectormap',
  map: "world",
  markers: [
    {
    "coords": [38, -97],
    "name": "United States"
    },
    {
    "coords": [20, 77],
    "name": "India"
    },
    {
    "coords": [60, -95],
    "name": "Canada"
    },
    {
    "coords": [51, 9],
    "name": "Germany"
    },
    {
    "coords": [54, -2],
    "name": "United Kingdom"
    }
  ],
});
			
test.addMarkers([{
  name: 'Russia',
  coords: [61, 105],
  label: 'Russia',
  offsets: [15, 10],
  style: { fill: 'red' }
}]);
```

I've got an error

jsvectormap.min.js:1 Uncaught TypeError: Cannot read property 'createGroup' of undefined
    at t.createMarkers (jsvectormap.min.js:1)
    at t.e.addMarkers (jsvectormap.min.js:1)
    at dashboard-alternative.html:3513
    at dashboard-alternative.html:3525

**Comment by themustafaomar** [comment]
Hey @o2sevruk

This is somehow doesn't work because it seems that the map hasn't been loaded yet, and actually, it doesn't make sense to call `addMarkers` method without an event for example, instead, you should've added that marker inside `markers` property.

However, If you want to really do that you can call `addMarkers` inside `onLoaded` event.

```javascript
const jvm = new jsVectorMap({
  // ...
  onLoaded(map) {
    map.addMarkers([{
      name: "Russia",
      coords: [61, 105],
      label: "Russia",
      style: { fill: "red" }
    }]);
  },
  // ...
})
```

Example at Codepen: https://codepen.io/themustafaomar/pen/PombaQj

**Comment by o2sevruk** [comment]
@themustafaomar Hello!
How can I add new markers when some event appeared?
E.g. when some button is clicked some new items should be added to the existing.
